version: '3.1'

services:
  php:
    container_name: php
    build: ./php
    volumes:
      - ../:/var/www/html
      - ./htaccess:/etc/apache2/sites-enabled
    ports:
      - 8081:80

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123'

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1